themes/dljs/layout/index.hbs

This makes the getting started instructions more explicit for the two different workflows of script tag vs npm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/123)

make getting started more explicit for the two different paths

---

themes/dljs/helper/index.js
themes/dljs/layout/partials/header.hbs
themes/dljs/source/css/layout.scss

Using codepen, the new Try it button
Would open
Ready for people to edit and save to their own codepen accounts should they choose to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/128)

A browser playground proposal

---

source/tutorials/mnist.md

There was a mistake on the documentation, saying "low-lower linear algebra". I fixed it to "lower-level linear algebra", which makes more sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/179)

Correct 'low-lower linear' to 'lower-level linear'

---

source/tutorials/model-save-load.md

On the page Model-save-load it says "Trigger file **downlads** (Browser)" under Saving tf.model
I think it is obvious that this should be downloads.
The following are the details
https://github.com/tensorflow/tfjs/issues/556
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/185)

Spelling mistake on js.tensorflow.org

---

docs/guides/tfjs-layers-for-keras-users.md

DOC
- This is the same as https://js.tensorflow.org/tutorials/tfjs-layers-for-keras-users.html, with additions at the end
- Use `fitDataset()` to train models using `tf.data.Dataset` objects
- Memory management of Layer and Model objects
- `tf.loadModel()` is replaced with `tf.loadLayersModel()` per the v1.0 API change.
Fixes https://github.com/tensorflow/tfjs/issues/1150
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/246)

Add docs/guides/tfjs-layers-for-keras-users.md

---

.gitignore
build-scripts/doc-gen/parser.ts
build-scripts/doc-gen/util.ts

We do this by using a negative lookbehind in the regex that replaces generics.
This PR also ignores the source/vis/local directory which always shows up when running a local build.
Before:
After (also with the change that unpacks the docs), notice return type:
Non-promise generics stay the same:
Fixes https://github.com/tensorflow/tfjs/issues/1316
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/271)

Allow Promise<T> to appear in API docs.

---

docs/tutorials/setup.md

`strictNullChecks` is true by default in new typescript projects unless explicitly configured otherwise. This PR hopes to clarify type errors seen when using TensorFlow with TypeScript such as the one seen here https://github.com/tensorflow/tfjs/issues/1241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/287)

Document TypeScript gotcha for people with `strictNullChecks: true`

---

docs/guide/tensors_operations.md

The line below **seems** to be _unintentionally duplicated_ under the **Tensors** section in the Tensors and Operations page, as the exact same line exists in the short description under the header **Tensors and operations**
> TensorFlow.js is a framework to define and run computations using tensors in JavaScript. A *tensor* is a generalization of vectors and matrices to higher dimensions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/293)

Remove duplicated line in tensor_operations.md

---

docs/guide/platform_environment.md

There seems to be a stray "\\" character under the **WebGL backend** section in [Platform and Environment page](https://www.tensorflow.org/js/guide/platform_environment)
It is highlighted in the image below ⬇️ 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/292)

Remove stray "\" in platform_environment.md

---

docs/guide/tensors_operations.md

I'll write this guide in the future, but for now just removing it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/306)

Remove non-existent link to backends guide

---

docs/guide/conversion.md

"tfhub.dev" is a relative URL, "https://tfhub.dev/" is absolute. Either the DevSite utils, or the browser, is rendering this link incorrectly. This should fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/314)

Fixing link to tfhub.

---

docs/guide/nodejs.md

The current documentation shows an example that will error out when running because of two reasons:
- no `inputShape`
- no `async`
This PR makes changes to make the code run if copy/pasted 👍
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/335)

add input shape and async

---

build-scripts/build-api.ts
build-scripts/doc-gen/util.ts

This fixes a bug in parsing docs for our next release (building docs against HEAD). The bug is caused by a bug in tsc, but revealed by some [new code added to the library](https://github.com/tensorflow/tfjs/pull/3702/files#diff-da3cd97c7099a88cc8e268c426d97188).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/376)

add fallback for missing valueDeclaration in interface parameters

---

docs-prerelease/custom_ops_kernels_gradients.md
docs-prerelease/size_optimized_bundles.md
docs-prerelease/upgrading_to_3_0.md

Add new guides and tutorials to website repo.
These are markdown versions of the docs in our team drive.
They are going into a `docs-prerelease` folder so that they can be linked to from the release ntoes and publicaly viewable. When the final release goes out these will be moved into the `docs` folder which automatically syncs with the tensorflow web site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/398)

3.0 guides and tutorials

---

docs-prerelease/upgrading_to_3_0.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/400)

fix links to markdown docs instead of google docs

---

devserver.js
package.json
yarn.lock

http-server has security vulnerabilities in its dependency `ecstatic@^3.3.2`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/409)

Replace http-server devserver with fastify

---

build-scripts/build-task-api.ts
build-scripts/build_api_helpers.ts
source/_data/api_tasks/skeleton.json

- Add cocossd and deeplab to the declaration file allow list.
- Set default value of the `allowedDeclarationFileSubpaths` flag to empty string with the quotes. Without doing this, the command line tool will consider it as missing argument.
- Add skeleton for image segmentation and object detection task.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/423)

Minor fixes for doc-gen

---

docs/tutorials/upgrading_to_3_0.md

Adding details for WebGPU package in the docs (https://www.tensorflow.org/js/tutorials/upgrading_to_3_0)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/466)

add webgpu as backend to upgrading_to_3_0 documentation

---

build-scripts/build-api.ts
build-scripts/build_api_helpers.ts
build-scripts/doc-gen/make-api.ts
build-scripts/doc-gen/parser.ts
build-scripts/doc-gen/util.ts
build-scripts/doc-gen/view.ts

This PR enables `yarn build-api` command to parse variables declared in [flagFiles](https://github.com/tensorflow/tfjs-website/pull/476/files#diff-f10d967e083e31273927d31911a476b660894628514efb9f71d0adc4676a01d8R68) and also enables it to parse single file without dependencies.
Specifically, for each file declared in [flagFiles](https://github.com/tensorflow/tfjs-website/pull/476/files#diff-f10d967e083e31273927d31911a476b660894628514efb9f71d0adc4676a01d8R68), the parser will traverse all `node`s if `ts.isVariableDeclaration(node)`.
For example, if webgl's flag file is declared in [flagFiles](https://github.com/tensorflow/tfjs-website/pull/476/files#diff-f10d967e083e31273927d31911a476b660894628514efb9f71d0adc4676a01d8R68), the following codes in the flag file
```js
/**
* Whether we will …
```

Enable API doc generation from a file and from variables

---

themes/tfjs/source/js/api.js

Fix https://github.com/tensorflow/tfjs/issues/7213.
In API webpage, both Toc area and Content area could be scrolled. 
Currently, when scrolling on Content area, `updateTocView` would always be triggered, causing Toc area automatically be scrolled. On the other side, when scrolling on Toc area, Content area should be scrolled.
However, when when TOC section's scroll position reaches bottom, Content area would be scrolled by default, causing the issue https://github.com/tensorflow/tfjs/issues/7213. This PR disables this default behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/485)

Fix scroll issse on API webpage

---

themes/tfjs/layout/layout.hbs

Since tensor creation API involves WebGPU backend, we could add WebGPU backend to the website to support users to try WebGPU backend's features.
Since the version of tfjs-backend-webgpu is not same as the version of tfjs union package, we could always use the latest version of it.
Fixed https://github.com/tensorflow/tfjs/issues/7289.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/488)

Add tfjs-backend-webgpu to API page

---

themes/tfjs/source/js/codeSnippets.js

Since WebGPU backend initialization is async, it requires call `tf.ready()` or `tf.setBackend('webgpu')` before usage. Without calling `tf.ready()` or `tf.setBackend(backendName)`, it works for other backends, because all other backends' initializations are sync.
Fix: https://github.com/tensorflow/tfjs/issues/7688

Support code snippet running on WebGPU backend

---

docs/guide/layers_for_keras_users.md

I have updated the broken link for Layers API from old link https://js.tensorflow.org/api/latest/ to new link https://js.tensorflow.org/api/latest/#Layers. 
Please do the needful. Thank You !

Update broken link for Layers API.

---

docs/tutorials/upgrading_to_3_0.md

I have updated broken link on the page `Upgrading to TensorFlow.js 3.0 `for hyperlink `see this tutorial` under `Custom Modules` section from `size_optimized_bundles.md` to updated link `https://github.com/tensorflow/tfjs-website/blob/master/docs/tutorials/deployment/size_optimized_bundles.md` so please do the needful. Thank you!

Updated broken link

---

docs/guide/platform_environment.md

This pull request fixes a grammar mistake that used to make the documentation ambiguous.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/489)

fix: grammar
