source/faq/index.md
themes/dljs/layout/index.hbs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/98)

Some tiny copyedits: home page and FAQ

---

source/tutorials/core-concepts.md

Fixes code blocks in `core-concepts.md`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/106)

Fix code blocks in core-concepts.md

---

source/tutorials/fit-curve.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/108)

Fix tutorial typo

---

source/tutorials/tfjs-layers-for-keras-users.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/110)

Fix some syntax and comments in tfjs-layers-for-keras-users.md

---

themes/dljs/layout/partials/footer.hbs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/115)

Point to new TensorFlow blog

---

source/_data/api/skeleton.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/122)

Fix typo in skeleton for Models

---

source/_data/api/0.8.0/docs.json
source/_data/api/0.8.0/skeleton.json
themes/dljs/layout/layout.hbs

closes #118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/125)

 load the correct version of tfjs on docs pages

---

source/_data/api/0.6.1/docs.json
source/_data/api/0.6.1/tfjs-layers.json

closes #124
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/130)

Fix snippet bug in 0.6.1 

---

themes/dljs/layout/index.hbs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/134)

Fix perf-rnn link

---

source/tutorials/fit-curve.md
source/tutorials/webcam-transfer-learning.md

closes #121 and #129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/132)

small content fixes

---

themes/dljs/layout/index.hbs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/143)

fix baseball demo link

---

source/faq/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/144)

update faq to point to node bindings

---

source/tutorials/fit-curve.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/145)

Fixed typo from tf.train.sdg to tf.train.sgd

---

source/tutorials/mnist.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/146)

Fix incorrect redirect from mnist to fit-curve

---

source/tutorials/index.md
source/tutorials/model-save-load.md
source/tutorials/tfjs-layers-for-keras-users.md

Towards: https://github.com/tensorflow/tfjs/issues/13
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/147)

Add tutorial for saving and loading `tf.Model`

---

source/tutorials/index.md
source/tutorials/model-save-load.md

- Website doesn't render markdown tables correctly yet. Fall back
to HTML tables.
- Fix some plural/singular and backtics related to `tf.Model`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/152)

Fixes to model-save-load.md

---

source/faq/index.md

Related to: https://github.com/tensorflow/tfjs/issues/13
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/155)

Update answer related to model export

---

source/tutorials/core-concepts.md

Delete `)`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/156)

⚙️ Update core-concepts.md

---

themes/dljs/layout/index.hbs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/157)

Update the title to include Node.js

---

source/tutorials/mnist.md
source/tutorials/webcam-transfer-learning.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/163)

add yarn instructions to the two other tutorials

---

source/_data/api/skeleton.json

Organizes tensor5d along with related ops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/169)

Sorts tensor5d along with related ops

---

_config.yml

allows gfm style tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/171)

switch to github flavoured markdown

---

themes/dljs/layout/index.hbs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/172)

Fix capitalization on homepage

---

themes/dljs/layout/partials/header.hbs
themes/dljs/source/css/layout.scss

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/173)

add survey link

---

themes/dljs/source/css/api.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/174)

fix api header height after survey link change

---

themes/dljs/source/css/api.scss
themes/dljs/source/css/layout.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/175)

Header fix

---

themes/dljs/source/css/api.scss

This PR fixes https://github.com/tensorflow/tfjs/issues/496.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/177)

Fixes #496: Header overlays API select menu

---

themes/dljs/layout/partials/header.hbs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/178)

shorten survey link text to not be cut off on mobile

---

source/debug/index.html

Also call .data() instead of dataSync() since more flags are evaluated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/181)

Update debug page to show more env flags

---

build-scripts/doc-gen/parser.ts
build-scripts/doc-gen/util.ts
source/_data/api/skeleton.json

Also pin tensor6d.
Fixes https://github.com/tensorflow/tfjs/issues/356
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/183)

Add support for the spread operator.

---

themes/dljs/layout/partials/header.hbs
themes/dljs/source/css/layout.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/189)

remove survey link

---

source/tutorials/how-to-get-started.md
source/tutorials/index.md
themes/dljs/source/css/layout.scss

moved content to .md from google doc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/193)

add how to get started guide

---

source/tutorials/custom-webgl-op.md

fix some typos in `How to define a custom WebGL operation`.
Signed-off-by: Yihong Wang <yh.wang@ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/197)

fix some typos

---

source/tutorials/custom-webgl-op.md

following on from some typos fixed in #197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/198)

fix typo in custom op guide

---

themes/dljs/layout/index.hbs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/199)

link directly to minified file, enables source map to load correctly

---

source/tutorials/index.md

👨‍🏫
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/201)

Fix typo on Tutorials & Guides page

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/202)

Increase node memory limit which generating or serving site

---

source/tutorials/import-saved-model.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/216)

Fox broken link to mobilenet demo

---

themes/dljs/source/js/codeSnippets.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/218)

When logging rich objects, in API snippets call JSON.stringify() automatically so they render properly.

---

themes/dljs/layout/partials/apiToc.hbs
themes/dljs/source/css/api.scss

closes https://github.com/tensorflow/tfjs/issues/1034
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/223)

show class methods in api toc

---

docs/_book.yaml
docs/_index.yaml
docs/_project.yaml
docs/api_docs/README.md
docs/examples/bar_example.md
docs/examples/index.md
docs/foo_guide.md
docs/overview.md
docs/tutorials/baz_tutorial.md
docs/tutorials/index.md

Depends on cl/227778142 to import a new CL into the DevSite publishing area.
This demo is staged here: go/tfo-stage/js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/224)

Initial skeleton for TFJS subsite

---

themes/dljs/layout/setup.hbs

Removing semicolon (;) which is causing the code to fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/231)

Fixing code issue in setup page of js.tensorflow.org

---

source/tutorials/webcam-transfer-learning.md

Fixed an issue where the upper and lower lines of code could not be connected due to a wrong variable name. @wangtz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/226)

Fix variable name error.

---

themes/dljs/layout/setup.hbs

Will not submit until the next node release.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/222)

Update node documentation to return the tf symbol through the package.

---

source/tutorials/model-save-load.md

With document.getElementById, we can get element by id, cannot get by name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/239)

In two input element, changed name to id

---

docs/_book.yaml
docs/tutorials/learning/ml.md

This is the port of https://js.tensorflow.org/tutorials/how-to-get-started.html, however it has been slimmed down to just focus on ML resources and overall tries to provide fewer links (so as to not overwhelm with choice).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/241)

add ml learning resources

---

docs/tutorials/training/handwritten-digit-cnn.md
docs/tutorials/training/linear-regression.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/242)

add landing pages for training tutorials

---

docs/_book.yaml
docs/guides/platforms-environments.md
docs/guides/tensors-operations.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/244)

Add tensor/operations and platforms/environments guides

---

docs/_book.yaml
docs/guides/index.md
docs/guides/models-and-layers.md
docs/guides/training-models.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/245)

Add guides for intro, models, layers, training

---

docs/guides/models-and-layers.md
docs/guides/platforms-environments.md
docs/guides/tensors-operations.md
docs/guides/training-models.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/249)

fix list rendering

---

docs/guides/index.md
docs/guides/using-tfjs-in-node.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/252)

Add the Using TensorFlow.js in Node.js guide.

---

docs/tutorials/conversion/import-keras.md
docs/tutorials/conversion/import-saved-model.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/255)

Add conversion tutorials

---

docs/tutorials/training/saving-loading.md

Updated tutorial on saving and loading models.
This PR is a WIP as the loading part has not been written and is blocked by https://github.com/tensorflow/tfjs/issues/1175
Another issue fix which would be helpful for this is https://github.com/tensorflow/tfjs/issues/1207
However the first part is ready for review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/240)

Saving & loading tutorial

---

docs/guides/conversion.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/258)

Add guide to model conversion.

---

docs/_project.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/263)

Add project include file for banner

---

package.json
source/_data/api/skeleton.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/265)

Update yarn build-api to use local and update the skeleton to pin the new model loader methods.

---

docs/tutorials/index.md
docs/tutorials/learning/ml.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/268)

editorial changes

---

docs/tutorials/setup.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/266)

Update version in cdn link

---

source/tutorials/import-keras.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/280)

tf.fromPixels => tf.browser.fromPixels in tutorials

---

docs/guide/models_and_layers.md

`model.load => tf.loadLayerModel` in guide
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/289)

model.load => tf.loadLayerModel in guide

---

docs/tutorials/setup.md

remove semi-colon syntax error.
closes https://github.com/tensorflow/tensorflow/issues/27237
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/295)

Fix typo in code sample

---

cloudbuild.yml
package.json
scripts/cloud_funcs/README.md
scripts/cloud_funcs/trigger_nightly/.gcloudignore
scripts/cloud_funcs/trigger_nightly/index.js
scripts/cloud_funcs/trigger_nightly/package-lock.json
scripts/cloud_funcs/trigger_nightly/package.json
scripts/test-ci.sh

Migrate from Travis to Cloud Build and schedule a nightly run.
This change sets up the Cloud Build integration and adds a placeholder `scripts/test-ci.sh` to demonstrate how to write tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/297)

Migrate from Travis to Cloud Build and schedule a nightly run

---

firebase.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/299)

Redirect old custom op tutorial

---

docs/guide/tensors_operations.md
docs/tutorials/setup.md

Also remove mention of missing link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/313)

reword note on Tensor.array() and Tensor.data() to indicate they are async

---

docs/_book.yaml
docs/tutorials/training/nodejs_training.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/315)

add link to Node.js codelab

---

docs/guide/index.md

Need this title to display in site search. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/317)

Add title to guide/index

---

package.json
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/320)

Add firebase-tools to dev deps and a deploy prod script.

---

docs/guide/platform_environment.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/329)

Update precision section in guide

---

themes/tfjs/layout/partials/apiClass.hbs
themes/tfjs/layout/partials/apiFunction.hbs
themes/tfjs/source/css/api.scss

Closes https://github.com/tensorflow/tfjs/issues/389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/332)

Improve rendering of the 'optional' tag for params

---

package.json
yarn.lock

Resolves recent security warning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/334)

Update dependencies and remove obsolete ones

---

docs/tutorials/conversion/import_saved_model.md

Fix broken links and update tutorial
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/353)

Update docs import_saved_model.md

---

package.json
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/358)

Update dev deps version to remove security vulnerability

---

README.md
package.json
themes/tfjs/helper/index.js
yarn.lock

Fixes a broken build from a previous dependency upgrade. Also updates http-server to address security warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/362)

Fix hexo upgrade and update http-server

---

docs/tutorials/setup.md

Update the version string in the setup tutorial to point to 2.0
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/363)

update version string for script tag

---

themes/tfjs/helper/index.js
themes/tfjs/source/js/api.js
themes/tfjs/source/js/codeSnippets.js
themes/tfjs/source/js/layout.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/381)

add license headers to js files

---

docs/tutorials/index.md

Not sure if this is intentional, if so, feel free to reject!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/390)

Update heading size to match

---

docs/tutorials/conversion/import_saved_model.md

Pointing to new save and load TF Core page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/434)

Updating broken link on website

---

package.json
yarn.lock

fix security issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/438)

lock tar package version

---

docs/tutorials/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/464)

Updating documentation language for clarity

---

docs/_book.yaml
docs/_upper_tabs_api.yaml

See cl/393197013 for context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/tfjs-website/468)

link upper 'API' tab to the JS API, when you're on a js page.
